pub const RESET = "\x1b[0m"; // Reset to default color
pub const BLACK = "\x1b[30m"; // Black
pub const RED = "\x1b[31m"; // Red
pub const GREEN = "\x1b[32m"; // Green
pub const YELLOW = "\x1b[33m"; // Yellow
pub const BLUE = "\x1b[34m"; // Blue
pub const MAGENTA = "\x1b[35m"; // Magenta
pub const CYAN = "\x1b[36m"; // Cyan
pub const WHITE = "\x1b[37m"; // White
